# SPDX-License-Identifier: GPL-2.0+
#
#
obj-$(CONFIG_MMC_SUNXI)		+= sunxi_mmc_host_common.o
obj-$(CONFIG_MACH_SUN8IW21)		+= sun8iw21_unique.o
obj-y				+= sunxi_mmc_host_tm0.o sunxi_mmc_host_tm1.o \
 				   sunxi_mmc_host_tm4.o sunxi_mmc_host_tm5.o
