#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y	+= sunxi_timer.o

subdir-ccflags-$(CONFIG_SUNXI_FINS_FUNC_DRIVER_TIMER_DIR) += -finstrument-functions
