obj-y += clk_factor.o clk_periph.o clk.o clk_fixed_rate.o
obj-$(CONFIG_ARCH_SUN8IW10P1) += clk-sun8iw10.o
obj-$(CONFIG_ARCH_SUN8IW11P1) += clk-sun8iw11.o
obj-$(CONFIG_ARCH_SUN50IW1P1) += clk_sun50iw1.o
obj-$(CONFIG_ARCH_SUN50IW2P1) += clk-sun50iw2.o
