#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

COBJS-libufdt += ufdt_overlay.o ufdt_support.o ufdt_node.o ufdt_convert.o ufdt_node_pool.o ufdt_prop_dict.o

obj-$(CONFIG_OF_LIBUFDT) += $(COBJS-libufdt)
obj-$(CONFIG_FIT) += $(COBJS-libufdt)
