
#
# (C) Copyright 2017-2018
# Allwinner Technology Co., Ltd. <www.allwinnertech.com>
# wangwei <wangwei@allwinnertech.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += nand_osal.o

nand_osal-y  = ../../common0/osal/nand_osal_uboot.o
nand_osal-y += ../../common0/osal/nand_uboot_fun.o
nand_osal-y += ../../common0/osal/nand_lib_cfg.o



