#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= usbc.o
obj-y	+= usbc_dev.o
obj-y	+= usbc_dma.o
obj-y	+= usbc_host.o
obj-y	+= usbc_phy.o
