# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2007-2011
#Allwinner Technology Co., Ltd. <www.allwinnertech.com>
#Tom Cubie <tangliang@allwinnertech.com>


obj-y	+= cpu.o
obj-y	+= cache.o
obj-y	+= timer.o
