# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

ifdef CONFIG_VIDEO_STARFIVE
obj-y += sf_vop.o
obj-$(CONFIG_DISPLAY_STARFIVE_EDP) += sf_edp.o
obj-$(CONFIG_DISPLAY_STARFIVE_LVDS) += sf_lvds.o
obj-$(CONFIG_DISPLAY_STARFIVE_HDMI) += sf_hdmi.o
obj-$(CONFIG_DISPLAY_STARFIVE_MIPI) += sf_mipi.o
obj-$(CONFIG_VIDEO_NW_MIPI_DSI) += mipi_dsi_host.o
endif
