obj-$(CONFIG_SUNXI_MODULE_TV) += tv.o

tv-$(CONFIG_ARCH_SUN50IW1P1) := tv_ac200.o tv_ac200_lowlevel.o
tv-$(CONFIG_ARCH_SUN8IW11P1) := drv_tv.o de_tve_sun8iw11.o
tv-$(CONFIG_ARCH_SUN50IW2P1) := drv_tv.o de_tve_v1.o
