#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y	:= start.o
extra-y	+= spare_head.o
extra-y += uboot_hash.o


obj-y += console.o
obj-y += serial.o
obj-y += board_main.o

obj-y += mem_alloc.o

