obj-$(CONFIG_SUNXI_DISPLAY) += disp.o

disp-objs :=  dev_disp.o disp_sys_intf.o\
		de/lowlevel_v1x/de_be.o de/lowlevel_v1x/de_fe.o de/lowlevel_v1x/iep_drc_ebios.o de/lowlevel_v1x/iep_wb_ebios.o\
		de/lowlevel_v1x/iep_drc.o de/lowlevel_v1x/de_layer.o de/lowlevel_v1x/de_dsi.o de/lowlevel_v1x/de_lcd.o \
		de/disp_private.o de/disp_features.o de/lowlevel_v1x/disp_al.o de/lowlevel_v1x/sat.o \
		de/disp_display.o de/disp_private.o de/disp_features.o de/disp_lcd.o de/disp_layer.o de/disp_manager.o\
		de/disp_smart_backlight.o de/disp_capture.o de/disp_smart_color.o

disp-objs += lcd/lcd_source_interface.o lcd/panels.o lcd/default_panel.o lcd/tft720x1280.o\
            lcd/vvx10f004b00.o lcd/lp907qx.o lcd/starry768x1024.o lcd/sl698ph_720p.o lcd/B116XAN03.o lcd/u708_default_panel.o

