#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y += ../../arch/arm/cpu/armv7/sun50iw1p1/timer.o
obj-y += ../../arch/arm/cpu/armv7/sun50iw1p1/gic.o
obj-y += ../../arch/arm/cpu/armv7/sun50iw1p1/usb_clock.o
obj-y += ../../lib/initcall.o
obj-y += ../../arch/arm/cpu/armv7/lowlevel_init.o

obj-y += ../../common/sunxi_mem_alloc.o

