#
# (C) Copyright 2007-2016
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y += common/jcomapi.o common/jerror.o common/jmemmgr.o common/jutils.o

obj-y += decode/jdmerge.o decode/jidctint.o decode/jdcoefct.o decode/jidctfst.o			\
         decode/jdatasrc.o decode/jidctflt.o decode/jdcolor.o decode/picture_decoder.o	\
         decode/jdmaster.o decode/jdapistd.o decode/jquant2.o			\
         decode/jdsample.o decode/jdmainct.o decode/jquant1.o decode/jdapimin.o			\
         decode/jdpostct.o decode/jddctmgr.o decode/jdtrans.o decode/jdhuff.o			\
         decode/jdmarker.o decode/jdinput.o decode/jidctred.o decode/jdphuff.o

obj-y += sysdep/jmemnobs.o

obj-y += api/mydjpeg.o

