#
# Copyright (c) 2015 Allwinnertech, Inc.
# Tyle <tyle at allwinnertech.com>
#
#

obj-y += disp/
obj-$(CONFIG_SUNXI_MODULE_HDMI) += hdmi/
obj-$(CONFIG_SUNXI_MODULE_HDMI2) += hdmi2/
obj-$(CONFIG_SUNXI_MODULE_TV) += tv/
obj-$(CONFIG_EDP_DISP2_SUNXI) += edp/
