obj-y += phy/build_nand_partition.o \
	phy/build_phy_partition.o \
	phy/nand_info_init.o \
	physic_v2/chip/nand_chip_common.o \
	physic_v2/chip/nand_chip_function.o \
	physic_v2/chip/nand_chip_interface.o \
	physic_v2/chip/nand_super_chip_common.o \
	physic_v2/chip/nand_super_chip_function.o \
	physic_v2/chip/nand_super_chip_interface.o \
	physic_v2/controller/nand_controller.o \
	physic_v2/controller/nand_controller_common.o \
	physic_v2/controller/nand_controller_op.o \
	physic_v2/hynix16nm/nand1_chip_for_boot.o \
	physic_v2/hynix16nm_4G/nand8_chip_for_boot.o \
	physic_v2/hynix20nm/nand2_chip_for_boot.o \
	physic_v2/hynix26nm/nand3_chip_for_boot.o \
	physic_v2/nand_id2.o \
	physic_v2/nand_phy_init.o \
	physic_v2/nand_phyisc_interface.o \
	physic_v2/nand_platform_data.o \
	physic_v2/nand_secure_storage.o \
	physic_v2/uboot_tail.o \
	physic_v2/universal/nand0_chip_for_boot.o \
	physic_v2/universal/nand0_chip_op.o \
	physic_v2/universal/nand0_super_chip_op.o \
	physic_v2/version.o \
	phy_v2/build_phy_partition_v2.o \
	phy_v2/nand_info_init_v2.o
