
obj-$(CONFIG_ARCH_SUN50IW1P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN50IW2P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN8IW10P1) += sunxi_pwm_enhance.o
obj-$(CONFIG_ARCH_SUN8IW11P1) += sunxi_pwm_enhance.o

