
obj-$(CONFIG_ARCH_SUN50IW1P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN50IW2P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN50IW3P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN50IW6P1) += sunxi_pwm_sun50iw1p1.o
obj-$(CONFIG_ARCH_SUN8IW10P1) += sunxi_pwm_enhance.o
obj-$(CONFIG_ARCH_SUN8IW8P1) += sunxi_pwm_enhance.o
obj-$(CONFIG_ARCH_SUN8IW11P1) += sunxi_pwm_enhance.o
obj-$(CONFIG_ARCH_SUN8IW12P1) += sunxi_pwm_enhance.o
obj-$(CONFIG_ARCH_SUN3IW1P1)  += sunxi_pwm_sun3iw1p1.o
obj-$(CONFIG_ARCH_SUN8IW5P1) += sunxi_pwm_sun50iw1p1.o

