obj-$(CONFIG_SUNXI_MODULE_HDMI) += hdmi.o

hdmi-y := drv_hdmi.o hdmi_core.o hdmi_edid.o
hdmi-$(CONFIG_ARCH_SUN50IW1P1) += libhdmi_sun50iw1
hdmi-$(CONFIG_ARCH_SUN50IW2P1) += libhdmi_sun50iw1
hdmi-$(CONFIG_ARCH_SUN8IW11P1) += libhdmi_sun8iw11
