obj-$(CONFIG_SUNXI_MODULE_HDMI) += hdmi.o

hdmi-y := drv_hdmi.o hdmi_core.o hdmi_edid.o
hdmi-$(CONFIG_ARCH_SUN50IW1P1) += libhdmi_sun50iw1
hdmi-$(CONFIG_ARCH_SUN50IW2P1) += libhdmi_sun50iw1
hdmi-$(CONFIG_ARCH_SUN8IW11P1) += hdmi_bsp_sun8iw11.o
hdmi-$(CONFIG_ARCH_SUN8IW12P1) += hdmi_bsp_sun8iw12.o
hdmi-$(CONFIG_ARCH_SUN8IW7P1) += hdmi_bsp_sun8iw7.o
hdmi-$(CONFIG_ARCH_SUN8IW6P1) += hdmi_bsp_sun8iw6.o
