
##
## Makefile for Sunxi Secure Boot
##

#obj-y += aes_decrypt.o aes_encrypt.o cbc_mode.o ccm_mode.o cmac_mode.o ctr_mode.o ctr_prng.o ecb_mode.o ecc.o ecc_dh.o ecc_dsa.o hmac.o sha256.o utils.o
obj-y += ecc.o ecc_dsa.o

